### ISSUE TITLE
Add OpenLibrary!

### ISSUE THREAD

**Issue by daybugging** [fundevogel/pcbis2pdf#7]
Howdy,
for english books, this might be useful:
https://openlibrary.org

API documentation can be found [here](https://openlibrary.org/dev/docs/api/books), which is pretty straightforward (I guess, not an expert though ..), what do you think about this?

**Comment by S1SYPHOS** [comment]
I thought about that, too, but right now there seems little additional value, since we're dealing almost exlusively with german books. However, I'll whip something up when I find the time.

Stay tuned and thanks for your feedback, which is appreciated greatly.

**Comment by S1SYPHOS** [comment]
I added OpenLibrary support, be sure to try it with the following:

```php
<?php

include ('vendor/autoload.php');

$client = new PCBIS2PDF\Providers\OpenLibrary;
$result = $client->getBook('your-isbn-here');
```
.. and use whatever information suits your needs!
